name: cwa_admin_backend

services:
  workspace:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env.development
    ports:
      - 8000:8000
    depends_on:
      db:
        condition: service_started
    networks:
      - cwa-net
  db:
    image: postgres:16.4
    volumes:
      - ./scripts/init.sql:/docker-entrypoint-initdb.d/init.sql
      - postgres-data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    networks:
      - cwa-net
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=username
      - POSTGRES_DB=cwa
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U username"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 3s
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    networks:
      - cwa-net

volumes:
  postgres-data:

networks:
  cwa-net:
