name: cwa_admin_backend

services:
  workspace:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env.dev
    ports:
      - 8000:8000
    volumes:
      - .:/app
    depends_on:
      db:
        condition: service_started
    networks:
      - cwa-net
  db:
    image: postgres:16.4
    volumes:
      - ./scripts/init.sql:/docker-entrypoint-initdb.d/init.sql
      - postgres-data:/var/lib/postgresql/data
    env_file:
      - .env.dev
    ports:
      - 5432:5432
    networks:
      - cwa-net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 3s
    restart: on-failure
  adminer:
    image: adminer
    restart: on-failure
    ports:
      - 8080:8080
    networks:
      - cwa-net

volumes:
  postgres-data:

networks:
  cwa-net:
